### ISSUE TITLE
[Bug]: missing file despite it being there

### ISSUE THREAD

**Issue by iisoro** [Team-Resourceful/ResourcefulLib#10]
### Bug Description

![Screenshot 2024-03-12 155709](https://github.com/Team-Resourceful/ResourcefulLib/assets/163199452/49c0d753-6e55-4376-bfaa-5505c33e2d25)
initially i had creeper overhaul v3.0.2 with v2.1.2 of resourceful with no issues but upon adding enderman overhaul v1.0.4 neither mod will read the file. ive tried every version from 2.1.20 to 2.1.23 since those are what eo needs to no avail as well as using the oldest versions of each mod. no matter the version of the lib or the mods its still comes up as not installed. even without eo present co still won't read the lib.

### How to Reproduce?

.

### Expected Behavior

.

### Version

2.1.20+

### Mod Loader Version

Forge 1.20.1 47.2.20

### Logs or additional context

the picture i provided would count?

### Acknowledgement

- [X] I agree that I read the terms at the top of the page.

**Comment by ThatGravyBoat** [comment]
wrong library https://www.curseforge.com/minecraft/mc-mods/resourceful-config you want resourceful config and thats why you couldnt find them

**Comment by iisoro** [comment]
ah, my fault ty!
