### ISSUE TITLE
[Bug]: Can't connect to server (no Cyrilic characters in Heracles)

### ISSUE THREAD

**Issue by WimpieRatte** [Team-Resourceful/ResourcefulLib#13]
### Bug Description

Minecraft 1.20.1
Forge: 47.2.30
The same error message as https://github.com/Team-Resourceful/ResourcefulLib/issues/8

![2024-05-13_19 47 07](https://github.com/Team-Resourceful/ResourcefulLib/assets/42098550/2c01f53a-da68-4e13-a4b7-3bb5823b7721)

Unlike the above bug report though, I do not have any Cyrilic characters in my quests.
I realise it's possible that this might be due to a second type of issue on Heracles' side, but since the error mentions ResourcefulLib, I thought it better to first mention it here, just in case. I'll also mention this on the Heracles issues, of course, as I don't fully know which mod is guilty this time.

People are unable to join after they were in the first time.

Log is attached.

One way I found that clears it, is if I stop the server, then delete the data/heracles* files in the world and then start the server.
But then the same thing happens all over again.

### How to Reproduce?

1. Install "Colonies and Technologies" modpack
2. Start a server version (the following mods will need to be excluded on the server side: Panorama Screens, Footprint Particle, Embeddium, watermedia, better beds reforged, BiomeParticleWeather, cherished worlds, clean tooltips, completionist index, current game music track, distinguished potions, effect descriptions, equipment compare, essential, forgematica, helditemtooltips, improved sign editing, loading backgrounds, mafglib, mob plaques, modpack update checker, no resourcepack warnings, overflowing bars, seamless, slot cycler, splashy, trade uses, traveler's titles, WI Zoom, yeetus experimentus)
3. Join the server (first time should be fine)
4. Complete some quests and exit
5. Try to rejoin

### Expected Behavior

Be able to log into the server.

### Version

2.1.24

### Mod Loader Version

Prismlauncher 8.2

### Logs or additional context

[latest.log](https://github.com/Team-Resourceful/ResourcefulLib/files/15298947/latest.log)

### Acknowledgement

- [X] I agree that I read the terms at the top of the page.

**Comment by ThatGravyBoat** [comment]
Fixed in latest version
