### ISSUE TITLE
[Feature Request]: add 1.21.1 tag to 1.21

### ISSUE THREAD

**Issue by BugmanBugman** [Team-Resourceful/ResourcefulLib#19]
### Is your feature request related to a problem?

cant download the mod on 1.21.1 instances on a modlauncher

### Solution(s)

add 1.21.1 tag to it

### Mod Version

1.21.1

### Mod Loader Version

n/a

### Acknowledgement

- [X] I agree that I read the terms at the top of the page.

**Comment by BugmanBugman** [comment]
Any update on this?

**Comment by BugmanBugman** [comment]
Bumping, it should take only a second to tag it on curseforge for 1.21.1

**Comment by flyover0112** [comment]
Many mods depend on resourceful lib and config....please make them for 1.21.1
