### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by cabbagee16** [Team-Resourceful/ResourcefulLib#2]
### Bug Description

I am using Fabric 1.19.2. So I downloaded the file for ResourcefulLib 1.1.20 as that is the latest file for Minecraft 1.19.2. But whenever I try to load the game, it gives me this error. It says to use version 1.2.0, however that is not the version I need for 1.19.2. 

Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Resourceful Lib' (resourcefullib) 1.1.20 with version 1.2.0 or later.
Unmet dependency listing:
	 - Mod 'Handcrafted' (handcrafted) 2.0.4 requires version 1.2.0 or later of mod 'Resourceful Lib' (resourcefullib), but only the wrong version is present: 1.1.20!

### Version

1.1.20

### Mod Loader Version

1.19.2

### Acknowledgement

- [X] I agree that I read the terms at the top of the page.

**Comment by ThatGravyBoat** [comment]
handcrafted 2.0.4 is for 1.19.3 not 1.19.2

**Comment by ThatGravyBoat** [comment]
You need to get the correct handcrafted version for 1.19.2

**Comment by cabbagee16** [comment]
ohh you're so right i totally overlooked that. thank you!
