### ISSUE TITLE
[Bug]: Attempted to select a dependency jar message in MC 1.20.1 server logs

### ISSUE THREAD

**Issue by Norepinephrinee** [Team-Resourceful/ResourcefulLib#20]
### Bug Description

Message **[main/WARN] [ne.mi.ja.se.JarSelector/]: Attempted to select a dependency jar for JarJar which was passed in as source: resourcefullib. Using Mod File: /home/container/mods/[Library] Resourceful Lib (2.1.28).jar** appears in logs every time the server is started. Not a mod conflict.

Maybe it's fine or safe to ignore? I have zero understanding of coding, so, just to make sure.

### How to Reproduce?

Simply start the server.

### Expected Behavior

No messages like that?

### Version

Latest, 2.1.28

### Mod Loader Version

Forge 47.3.7 (the message also appeared with Forge 47.3.5 and Forge 47.3.1)

### Logs or additional context

Here's a full log, although there's nothing else wrong but this single message – [latest (15).log](https://github.com/user-attachments/files/16714669/latest.15.log)

### Acknowledgement

- [X] I agree that I read the terms at the top of the page.

**Comment by ThatGravyBoat** [comment]
it is fine, just means a mod is using rlib as a jar jar dependency
