### ISSUE TITLE
[Bug]: Game crashed when certain fluid is rendered

### ISSUE THREAD

**Issue by LeoLezury** [Team-Resourceful/ResourcefulLib#26]
### Bug Description

When searching "sugar" in EMI, the game instantly crashed, the log said java.lang.NullPointerException: Cannot invoke "com.teamresourceful.resourcefullib.client.fluid.data.ClientFluidProperties.tintColor(net.minecraft.class_1920, net.minecraft.class_2338, net.minecraft.class_3610)" because "this.properties" is null

### How to Reproduce?

1. Install EMI, The Bumblezone (requires ResourcefulLib), Tech Reborn
2. Search anything related to Sugar Water Cell (Fluid Cell from Tech Reborn, Sugar Water from The Bumblezone)
3. Crash

### Expected Behavior

No crash happen. Possible fix is change "properties" in https://github.com/Team-Resourceful/ResourcefulLib/blob/1.21.x/fabric/src/main/java/com/teamresourceful/resourcefullib/client/fluid/fabric/ResourcefulFluidRenderHandler.java#L72 to "properties()"

### Version

3.0.10

### Mod Loader Version

1.21.1 Fabric 0.16.5 API 0.105.0

### Logs or additional context

https://mclo.gs/MfbvKTQ

### Acknowledgement

- [X] I agree that I read the terms at the top of the page.

**Comment by ThatGravyBoat** [comment]
Fix in 3.0.11
