### ISSUE TITLE
[Bug]: version 1.2.7 shows as not installed

### ISSUE THREAD

**Issue by the-demoncore** [Team-Resourceful/ResourcefulLib#3]
### Bug Description

I add the mod to my mods folder so the handcrafted mod (version 2.1.0 for minecraft 1.19.3) and i get a message that says resourcefullib 1.2.7 needs to be installed.

### How to Reproduce?

1. use forge for minecraft 1.19.3
2. add handcrafted 2.1.0 and resourcefullib 1.2.7 to mods folder
3. load the game

### Version

1.2.7

### Mod Loader Version

forge 1.19.3 - 44.1.23

### Acknowledgement

- [X] I agree that I read the terms at the top of the page.

**Comment by ThatGravyBoat** [comment]
send the log for it

**Comment by the-demoncore** [comment]
[latest.log](https://github.com/Team-Resourceful/ResourcefulLib/files/10962927/latest.log)

**Comment by ThatGravyBoat** [comment]
are you 100% sure you put it in the folder because it doesnt seem you have any version of the mod at all

**Comment by the-demoncore** [comment]
huh weird, ive put it in the folder all my other mods go
