### ISSUE TITLE
[Bug]: Fresh Animations Resource Pack Not Compatible

### ISSUE THREAD

**Issue by dexula** [Team-Resourceful/ResourcefulLib#5]
### Bug Description

ResourcefulLib **enabled**:
![image](https://github.com/Team-Resourceful/ResourcefulLib/assets/116233696/83612e35-b897-4835-ba94-98494cc324a2)

ResourcefulLib **disabled**:
![image](https://github.com/Team-Resourceful/ResourcefulLib/assets/116233696/7d31e848-4255-48db-a091-2769ff0481bf)

### How to Reproduce?

1. Have [Entity Model Features](https://modrinth.com/mod/entity-model-features) Mod
2. Have [Entity Texture Features](https://modrinth.com/mod/entitytexturefeatures) Mod
3. Have [Fresh Animations](https://www.curseforge.com/minecraft/texture-packs/fresh-animations) Resource Pack
4. Have [Fresh Animations - Extensions](https://www.curseforge.com/minecraft/texture-packs/fresh-animations-extensions) Resource Pack
5. Test

### Version

2.0.8

### Mod Loader Version

Fabric 0.14.21-1.20

### Logs or additional context

https://gist.github.com/dexula/5b0de74830ebc7a4975e394a11b114cb

### Acknowledgement

- [X] I agree that I read the terms at the top of the page.

**Comment by ThatGravyBoat** [comment]
is that mod list of without resourcefullib?

**Comment by dexula** [comment]
@ThatGravyBoat 
Are you referring to the Force Crash Report (Link under "Logs or additional context")?
If you are then no, it is without ResourcefulLib. I apologize. I force crashed it without realizing I had it disabled.

I am going to run more tests. I did not expect a quick response and will update further results

**Comment by dexula** [comment]
oops

**Comment by ThatGravyBoat** [comment]
Well just letting you know that because you use my Iron Chests mod it includes Resourceful Lib inside so I don't think this bug is actually caused by Resourceful Lib because you have Resourceful Lib loaded from the Iron Chests mod

**Comment by dexula** [comment]
You may be right. Right now, I just tested a superflat world increasing the maximum ram to 8gb and everything seems to be working. 

However, earlier before I started this post, I was looking for the issue and started removing mods and reenabling them one by one. And every time I enabled ResourcefulLib, the horses' textures started malfunctioning. And whenever I took out ResoucefulLib, the horses went back to normal (See Images above). And so that's why I thought ResoucefulLib was the main issue.

I'm going to re-do the process and start from scratch. Basically enable mods one by one and see which is the culprit. I apologize for the time I took away from you and I appreciate the really quick responses

**Comment by dexula** [comment]
@ThatGravyBoat 
I concluded that the [Earth2Java](https://modrinth.com/mod/earth2java) mod is responsible for this issue.

However, there was one instance that everything was completely okay even though both Earth2Java and ResourcefulLib were enabled. After disabling the FA resourcepack then enabling it after, the textures still continued to malfunction.

The other 9/10 times, with Earth2Java enabled, the textures still malfunctioned nonetheless.
The other 1-3/10 times, with Earth2Java disabled and only ResourcefulLib enabled with other mods, the textures sometimes don't work properly; like the mooblooms don't have any mushrooms on them at all and uses the vanilla animations. I'm not 100% sure what is going on but all I can conclude is that it is not a ResourcefulLib issue.

I apologize for any inconvenience, however if someone other than me receives this issue, you have my input/data to use.
