### ISSUE TITLE
[Bug]: Can't connect to a server

### ISSUE THREAD

**Issue by Proxwian** [Team-Resourceful/ResourcefulLib#8]
### Bug Description

Basically got only the error on the screen, no errors in server/client log

### How to Reproduce?

1. Install OxMODPACK: TFC 0.8.0 modpack
2. Try to join the server

### Expected Behavior

Player can join the server

### Version

2.1.21

### Mod Loader Version

47.2.20

### Logs or additional context

![image](https://github.com/Team-Resourceful/ResourcefulLib/assets/31781674/6e3fd28f-0934-4f60-8e3c-14b1ca787c6b)

### Acknowledgement

- [X] I agree that I read the terms at the top of the page.

**Comment by ThatGravyBoat** [comment]
need the whole log

**Comment by Proxwian** [comment]
[latest.log](https://github.com/Team-Resourceful/ResourcefulLib/files/14129921/latest.log)

**Comment by Proxwian** [comment]
yay, this time got an error in log

**Comment by Proxwian** [comment]
Looks like error with the Heracles mod and ciryllic symbols. Any idea that problem in RLib itself?

**Comment by ThatGravyBoat** [comment]
its not an rlib issue its an issue in heracles itself, but make sure the heracles version on server and client match. But report it on the heracles issue tracker so it can be handled there.
