### ISSUE TITLE
Not exactly a bug but rather missing version[Bug]: 

### ISSUE THREAD

**Issue by NewAgeSoldier** [Team-Resourceful/ResourcefulLib#9]
### Bug Description

As there was no "Missing version" tab here... Uhm, this is probably the best way to send this : 

Resourceful Config is for 1.20.1 NeoForge but not Lib, which is strange I think, however... I can live without the mod for the time being as I just wanna test the mod in the image and don't know yet how good it is.. Just thought I should mention this somewhere somehow
![Bilde_2024-03-04_161637095](https://github.com/Team-Resourceful/ResourcefulLib/assets/10442785/0c9a2278-a78c-4baf-b8d9-9aca5653db73)

### How to Reproduce?

Don't know what to put here

### Expected Behavior

I honestly don't know what to put here

### Version

2.1.7 or above is needed

### Mod Loader Version

NeoForge 1.20.1 47.1.99

### Logs or additional context

Log would pretty much be the provided image I believe

### Acknowledgement

- [X] I agree that I read the terms at the top of the page.

**Comment by ThatGravyBoat** [comment]
You can use the forge version on neoforge

**Comment by ThatGravyBoat** [comment]
for 1.20.1

**Comment by NewAgeSoldier** [comment]
> You can use the forge version on neoforge

Oh okay, did not know that... Tried that few months back and only got crashes
